# controls how many profiles in line are rendered for different screens (bootstrap IDs)
view:
  profilesPerXSmall: 1
  profilesPerSmall: 2
  profilesPerMedium: 6
  profilesPerLarge: 6

categories:
  # - name: category title
  #   id: ID to refer to this category
  #   hidden: controls if this category is initially hidden on the webpage
  #   sort: order of this category (lower number -> higher on the webpage)

  - name: Faculty
    id: faculty
    hidden: false
    sort: 1

  # - name: Postdocs
  #   id: postdocs
  #   hidden: false
  #   sort: 2

  # - name: Graduate Students
  #   id: students
  #   hidden: false
  #   sort: 3

  - name: Researchers
    id: students
    hidden: false
    sort: 3

  - name: Alumni
    id: alumni
    hidden: true
    sort: 4

# people are sorted by the last name within a category #not anymore
people:
  # - name: full name
  #   image: image file name (with extension) from website/assets/images/people
  #   position: position title
  #   website: OPTIONAL. Full URL to personal page.
  #   category: ID of the category
  #   when: this is the time of arrival (for current members) or departure (for alumni) used to sort people. Should be changed from arrival year to departure year when someone becomes alumni

  # faculty

  - name: Mark Crovella
    image: crovella.png
    position: Professor
    website: https://www.cs.bu.edu/fac/crovella/
    category: faculty
    when: 1994

  - name: George Kollios
    image: kollios.jpg
    position: Professor
    website: https://www.cs.bu.edu/~gkollios/
    category: faculty
    when: 2000

  - name: Evimaria Terzi
    image: evimaria.jpg
    position: Professor
    website: http://cs-people.bu.edu/evimaria/
    category: faculty
    when: 2009

  - name: Manos Athanassoulis
    image: manos.jpg
    position: Associate Professor
    website: https://cs-people.bu.edu/mathan/
    category: faculty
    when: 2019

  - name: Kyle Deeds
    image: kyle-deeds.jpg
    position: Assistant Professor
    website: https://kylebd99.github.io/kyle.deeds.github.io/
    category: faculty
    when: 2026

  - name: Charalampos Tsourakakis
    image: babis.jpg
    position: Adjunct Faculty
    website: https://tsourakakis.com/
    category: faculty
    when: 2024

  # active researchers

  - name: Xiyue Gao
    image: xiyue-gao-visiting-faculty.jpg
    position: Visiting Faculty
    website: https://scholar.google.com.hk/citations?user=grbVcy4AAAAJ&hl=en
    category: students
    when: 2024

  - name: Andy Huynh
    image: andy.jpg
    position: PhD Researcher
    website: http://cs-people.bu.edu/ndhuynh/
    category: students
    when: 2017
  
  - name: Karan Vombatkere
    image: Karan.jpeg
    position: PhD Researcher
    website: https://cs-people.bu.edu/kvombat/
    category: students
    when: 2021

  - name: Gabriel Franco
    image: gabriel_franco.jpeg
    position: PhD Researcher
    website: https://cs-people.bu.edu/gvfranco/
    category: students
    when: 2021

  - name: Teona Bagashvili
    image: teona.png
    position: PhD Researcher
    website: https://cs-people.bu.edu/teona/
    category: students
    when: 2022

  - name: Iasonas Nikolaou
    image: iasonas.jpg
    position: PhD Researcher
    website: https://jasonnikolaou.github.io/
    category: students
    when: 2022

  - name: Kevin B Quinn
    image: Kevin-Quinn.jpeg
    position: PhD Researcher
    website: https://www.bu.edu/cds-faculty/profile/kevin-quinn/
    category: students
    when: 2023

  - name: Themistoklis Nikas
    image: themis.jpg
    position: PhD Researcher
    website: https://cs-people.bu.edu/tnikas/
    category: students
    when: 2023

  - name: Anwesha Saha
    image: anwesha-saha.jpg
    position: PhD Researcher
    website: https://cs-people.bu.edu/anwesha/
    category: students
    when: 2024

  - name: Andrew Briasco-Stewart
    image: andrew-briasco-stewart.jpg
    position: PhD Researcher
    website: https://cs-people.bu.edu/abriasco/
    category: students
    when: 2025


  - name: Jovan Kascelan
    image: placeholder-male.png
    position: PhD Researcher
    website: https://cs-people.bu.edu/kascelan/
    category: students
    when: 2025


# alumni

  - name: Charalampos Mavroforakis
    image: harry.png
    position: "PhD (Next: Facebook)"
    website: https://www.linkedin.com/in/harrymvr
    category: alumni
    when: 2018

  - name: Sanaz Bahargam
    image: sanaz.jpg
    position: "PhD (Next: Twitter)"
    website: https://sanazbahargam.github.io/
    category: alumni
    when: 2017

  - name: Natali Ruchansky
    image: natali.jpg
    position: "PhD (Next: Postdoc at USC)"
    website: https://www.linkedin.com/in/nataliru/
    category: alumni
    when: 2016

  - name: Behzad Golshan
    image: behzad.jpeg
    position: "PhD (Next: Megagon Labs)"
    website: http://behzad.io/
    category: alumni
    when: 2016

  - name: Xianrui Meng
    image: xianrui.jpg
    position: "PhD (Next: Amazon)"
    website: https://www.xianruimeng.org/
    category: alumni
    when: 2016

  - name: Haohan Zhu
    image: haohan.jpg
    position: "PhD (Next: Facebook)"
    website: http://zhuhaohan.com/
    category: alumni
    when: 2016

  - name: Dora Erdos
    image: dori.jpg
    position: "PhD (Next: Postdoc at Brown University)"
    website: http://cs-people.bu.edu/edori/
    category: alumni
    when: 2015

  - name: Esther Galbrun
    image: esther.jpg
    position: "Postdoc (Next: Postdoc at INRIA Nancy)"
    website: https://members.loria.fr/EGalbrun/
    category: alumni
    when: 2015

  - name: Theodoros Lappas
    image: ted.jpg
    position: "Postdoc (Next: Faculty at Stevens Institute of Technology)"
    website: http://tedlappas.com/
    category: alumni
    when: 2013

  - name: Vassilis Athitsos
    image: vassilis.jpg
    position: "PhD & Postdoc (Next: Faculty at UT Arlington)"
    website: http://vlm1.uta.edu/~athitsos/
    category: alumni
    when: 2007

  - name: Marios Hadjieleftheriou
    image: marios.jpg
    position: "Postdoc (Next: AT&amp;T Labs)"
    website: http://hadjieleftheriou.com/
    category: alumni
    when: 2010

  - name: Feifei Li
    image: feifei.jpg
    position: "PhD (Next: Faculty at Florida State University)"
    website: http://www.cs.utah.edu/~lifeifei/
    category: alumni
    when: 2007

  - name: Panagiotis Papapetrou
    image: panagiotis.jpg
    position: "PhD (Next: Postdoc at Aalto University)"
    website: https://papapetrou.blogs.dsv.su.se/
    category: alumni
    when: 2009

  - name: Michalis Potamias
    image: michalis.jpg
    position: "PhD (Next: Groupon)"
    website: https://www.linkedin.com/in/mpotamias/
    category: alumni
    when: 2011

  - name: Georgios Kellaris
    image: kellaris.jpeg
    position: "Postdoc (Next: Co-Founder at Kalepso)"
    website: https://www.linkedin.com/in/gkellaris/
    category: alumni
    when: 2017

  - name: Bashir Rastegarpanah
    image: bashir.jpg
    position: "PhD (Next: Fiddler AI)"
    website: https://www.linkedin.com/in/bashir-rastegarpanah-56422839/
    category: alumni
    when: 2021

  - name: Harshal Chaudhari
    image: harshal.jpg
    position: "PhD (Next: Etsy)"
    website: https://harshalc.com/
    category: alumni
    when: 2021

  - name: Sofia Maria Nikolakaki
    image: sofia.jpg
    position: "PhD (Next: Apple)"
    website: http://www.smnikolakaki.com/
    category: alumni
    when: 2021

  - name: Dmytro Bogatov
    image: dmytro.jpeg
    position: "PhD (Next: AWS)"
    website: https://dbogatov.org/
    category: alumni
    when: 2022

  - name: Subhadeep Sarkar
    image: subjadeep.jpeg
    position: "Postdoc (Next: Faculty at Brandeis University)"
    website: https://subhadeep.net/
    category: alumni
    when: 2023

  - name: Ju Hyoung Mun
    image: juhyoung.jpg
    position: "Postdoc (Next: Faculty at Brandeis University)"
    website: https://sites.google.com/view/juhyoungmun/
    category: alumni
    when: 2024

  - name: Tianyi Chen
    image: tianyi.png
    position: "PhD (Next: Celonis)"
    website: https://www.linkedin.com/in/tianyi-chen-609939145/
    category: alumni
    when: 2024

  - name: Konstantinos Karatsenidis
    image: KostasKaratsenidis.jpg
    position: "Grad Researcher (Next: Tower Research Capital)"
    website: https://www.linkedin.com/in/karatse/
    category: alumni
    when: 2025  

  - name: Konstantinos Sotiropoulos
    image: sotiropoulos.jpg
    position: "PhD (Next: Postdoc at CMU)"
    website: https://www.linkedin.com/in/konstantinos-sotiropoulos-738755178/
    category: alumni
    when: 2023

  - name: Nathan Cordner
    image: nathan.jpg
    position: "PhD (Next: Faculty at Utah Valley University)"
    website: https://www.linkedin.com/in/nathan-cordner-504901aa/
    category: alumni
    when: 2023

  - name: Tarikul Islam Papon
    image: papon.jpg
    position: "PhD (Next: Faculty at UMass Boston)"
    website: https://www.cs.umb.edu/~tpapon/
    category: alumni
    when: 2025

  - name: Zichen Zhu
    image: zichen.jpg
    position: "PhD (Next: Google)"
    website: https://cs-people.bu.edu/zczhu/
    category: alumni
    when: 2025

  - name: Dimitris Staratzis
    image: dimitris.jpg
    position: "Grad Researcher (Next: TileDB)"
    website: https://www.linkedin.com/in/dimitris-staratzis-4b388b170/
    category: alumni
    when: 2020

  - name: Lina Qiu
    image: lina.jpg
    position: "PhD (Next: Huawei)"
    website: https://www.linkedin.com/in/lina-qiu-8a97b3147/
    category: alumni
    when: 2025
  
  - name: Aneesh Raman
    image: aneesh.jpg
    position: "PhD (Next: Salesforce)"
    website: https://www.linkedin.com/in/aneesh-raman/
    category: alumni
    when: 2025